- hosts: localhost
  gather_facts: no
  vars:
    region: ap-southeast-2
  tasks:
    - name: delete mysql RDS instance
      local_action:
        module: rds
        command: delete
        region: "{{ region }}"
        instance_name: staging-mysql-1 
