---
- hosts: localhost
  gather_facts: no
  vars:
    bucketname: yan001
  tasks:
    - name: create an S3 bucket
      local_action:
        module: s3
        bucket: "{{ bucketname }}"
        mode: create
