---
- hosts: localhost
  gather_facts: no
  vars:
    bucketname: yan001
  tasks:
    - name: delete an S3 bucket and all of its contents
      local_action:
        module: s3
        bucket: "{{ bucketname }}"
        mode: delete
