---
- hosts: localhost
  gather_facts: no
  vars:
    bucketname: yan001
  tasks:
    - name: upload file
      local_action:
        module: s3
        bucket: "{{ bucketname }}"
        object: /backup/database/test.txt
        src: test.txt
        overwrite: no
        mode: put
