---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-southeast-2
  vars_files:
    - staging_vpc_info
  tasks:
    - name: delete vpc
      local_action:
        module: ec2_vpc
        region: "{{ region }}"
        state: absent
        # get the vpc_id from staging_vpc_info file
        vpc_id: "{{ staging_vpc }}" 
        wait: yes
