---
- hosts: localhost
  gather_facts: no
  vars:
    #your region
    region: ap-southeast-2
    keyname: wordpress-apsydney
    instance_type: t2.micro
    image: ami-d9fe9be3
  tasks:
    - name: get staging_subnet_public_0 subnet id
      command: aws ec2 describe-subnets 
               --filters Name=tag:Name,Values=staging_subnet_public_0
               --query 'Subnets[0].SubnetId' --output text
      register: subnet0
    - name: launch ec2 instance
      tags: wp_master
      ec2:
        region: "{{ region }}"
        key_name: "{{ keyname }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: staging_sg_web
        id: wordpress_ha_5
        instance_tags:
          Name: wordpress_master
          class: wordpress_ha
        vpc_subnet_id: "{{ subnet0.stdout }}"
      register: ec2
    - name: associate new EIP for the instance
      tags: wp_eip
      ec2_eip:
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
      with_items: ec2.instances
      when: item.id is defined

