---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-southeast-2
    size: 100
    instance_type: db.m1.small
    db_engine: MySQL
    engine_version: 5.6.22
    subnet_group: dbsg_wordpress
    param_group: wordpress
    # staging_sg_database security group ID
    security_groups: sg-eeb14e8b
    iops: 1000
  tasks:
    - name: get staging_subnet_private_0 subnet id
      command: aws ec2 describe-subnets --filters Name=tag:Name,Values=staging_subnet_private_0
               --query 'Subnets[0].SubnetId' --output text
      register: subnet0
    
    - name: get staging_subnet_private_1 subnet id
      command: aws ec2 describe-subnets --filters Name=tag:Name,Values=staging_subnet_private_1
               --query 'Subnets[0].SubnetId' --output text
      register: subnet1

    - name: create Multi-AZ DB subnet group
      rds_subnet_group:
        name: "{{ subnet_group }}"
        state: present
        region: "{{ region }}"
        description: DB Subnet Group for WordPress HA
        subnets:
          - "{{ subnet0.stdout }}"
          - "{{ subnet1.stdout }}"

    - name: create mysql parameter group
      rds_param_group:
        name: "{{ param_group }}"
        state: present
        region: "{{ region }}"
        description: MySQL Parameter Group for WordPress HA
        engine: mysql5.6
        params:
          innodb_lock_wait_timeout: 3600
          max_allowed_packet: 512M
          net_write_timeout: 300

    - name: create mysql RDS instance
      rds:
        command: create
        instance_name: staging-wordpress-rds
        region: "{{ region }}"
        size: "{{ size }}"
        instance_type: "{{ instance_type }}"
        db_engine: "{{ db_engine }}"
        engine_version: "{{ engine_version }}"
        subnet: "{{ subnet_group }}"
        parameter_group: "{{ param_group }}"
        multi_zone: yes
        db_name: "{{ db_name }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vpc_security_groups: "{{ security_groups }}"
        iops: "{{ iops }}"


    
